on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  read_env:
    env:
      local: ${{ vars.local }}
      supersecret: ${{ secrets.supersecret }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read environment variable
        run: |
          echo ${{ vars.local }}
          echo ${{ secrets.supersecret }}
